####   Name:     Yared Tsegaye Gizaw
####         ID:     UGR/8284/12
#### Stream:     AI

In [1]:
import torch

In [2]:
class DenseLayer:
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

In [3]:
class Activation_Linear:
  # Forward pass
  def forward(self, inputs):
    self.output = self.output
    return self.ouput

In [4]:
class Activation_Sigmoid:
  # Forward pass
  def forward(self, inputs):
    self.output = 1 / (1 + torch.exp(inputs*-1))

In [5]:
X = torch.tensor([0.1, 0.5])
y = torch.tensor([0.05, 0.95])

In [6]:
hidden_layer_1 = DenseLayer(2, 4)
activation1 = Activation_Sigmoid()
output_layer = DenseLayer(4, 2)
activation2 = Activation_Linear()

In [7]:
def forward_pass(X):
  hidden_layer_1.forward(X)
  activation1.forward(hidden_layer_1.output)
  output_layer.forward(activation1.output)
  activation2.forward(output_layer.output)
  return activation2.output

In [18]:
def back_prop(fp):
  lr = torch.tensor(0.01)
  back1 = (fp[0][0]-y[0])*(1-fp[0][0])*fp[0][0]
  back2 = (fp[0][1]-y[1])*(1-fp[0][1])*fp[0][1]

  output_layer.weights[0][0] -= lr * back1*activation1.output[0][0]
  output_layer.weights[0][1] -= lr * back1*activation1.output[0][1]
  output_layer.weights[0][2] -= lr * back1*activation1.output[0][2]
  output_layer.weights[0][3] -= lr * back1*activation1.output[0][3]
  output_layer.weights[1][0] -= lr * back2*activation1.output[0][0]
  output_layer.weights[1][1] -= lr * back2*activation1.output[0][1]
  output_layer.weights[1][2] -= lr * back2*activation1.output[0][2]
  output_layer.weights[1][3] -= lr * back2*activation1.output[0][3]
  
  output_layer.biases[0][0] -= lr * back1
  output_layer.biases[0][1] -= lr * back2
  

  hidden_layer_1.weights[0][0] -= lr * (back1 * output_layer.weights[0][0] * X[0] + back2 * output_layer.weights[0][1] * X[0] ) 
  hidden_layer_1.weights[0][1] -= lr * (back1 * output_layer.weights[0][0] * X[1] + back2 * output_layer.weights[0][1] * X[1] ) 
  hidden_layer_1.weights[1][0] -= lr * (back1 * output_layer.weights[1][0] * X[0] + back2 * output_layer.weights[1][1] * X[0] ) 
  hidden_layer_1.weights[1][1] -= lr * (back1 * output_layer.weights[1][0] * X[1] + back2 * output_layer.weights[1][1] * X[1] ) 
  hidden_layer_1.weights[2][0] -= lr * (back1 * output_layer.weights[0][0] * X[1] + back2 * output_layer.weights[0][1] * X[1] ) 
  hidden_layer_1.weights[2][1] -= lr * (back1 * output_layer.weights[0][0] * X[1] + back2 * output_layer.weights[0][1] * X[1] ) 
  hidden_layer_1.weights[3][0] -= lr * (back1 * output_layer.weights[0][0] * X[1] + back2 * output_layer.weights[0][1] * X[1] ) 
  hidden_layer_1.weights[3][1] -= lr * (back1 * output_layer.weights[0][0] * X[1] + back2 * output_layer.weights[0][1] * X[1] ) 

  hidden_layer_1.biases[0][0] -= lr * (back1 * output_layer.weights[0][0] + back2 * output_layer.weights[0][1] ) if hidden_layer_1.output[0][0] > 0 else 0
  hidden_layer_1.biases[0][1] -= lr * (back1 * output_layer.weights[1][0] + back2 * output_layer.weights[1][1] ) if hidden_layer_1.output[0][1] > 0 else 0


In [19]:
def error_calculation(y_true, y_pred):
  return torch.mean(0.5*(y_true - y_pred)**2)

In [20]:
loss = 0.0001

In [ ]:
y_pred = forward_pass(X)
err = error_calculation(y, y_pred)
print("Initial loss:", err)
print("Initial prediction:",y_pred)
print(output_layer.weights)
print(activation1.output)
print(y_pred)
while err > loss:
  back_prop(y_pred)
  y_pred = forward_pass(X)
  err = error_calculation(y, y_pred)
print("Final loss:", err)
print("Final prediction:",y_pred)
print("Target value:",y)

Initial loss: tensor(0.0315)
Initial prediction: tensor([[0.0502, 0.9498, 0.5000, 0.5000]])
tensor([[ 2.6393e-03, -9.2831e-03,  7.6259e-03,  7.1674e-03],
        [ 5.8659e-03,  1.4986e-02,  9.7762e-03,  8.2954e-03],
        [ 4.7403e-03,  8.4073e-04,  4.5200e-03,  5.4192e-03],
        [ 7.9302e-03,  2.3355e-03,  9.7628e-05,  9.1641e-03]])
tensor([[0.0000, 0.0104, 0.0004, 0.0042]])
tensor([[0.0502, 0.9498, 0.5000, 0.5000]])
