####   Name:     Yared Tsegaye Gizaw
####         ID:     UGR/8284/12
#### Stream:     AI

In [1]:
import torch

In [2]:
class DenseLayer:
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

In [3]:
class Activation_Linear:
  # Forward pass
  def forward(self, inputs):
    self.output = inputs
    

In [4]:
class Activation_Sigmoid:
  # Forward pass
  def forward(self, inputs):
    self.output = 1 / (1 + torch.exp(inputs*-1))

In [5]:
X = torch.tensor([0.1, 0.5])
y = torch.tensor([0.05, 0.95])

In [6]:
hidden_layer_1 = DenseLayer(2, 4)
activation1 = Activation_Sigmoid()
output_layer = DenseLayer(4, 2)
activation2 = Activation_Linear()

In [7]:
def forward_pass(X):
  hidden_layer_1.forward(X)
  activation1.forward(hidden_layer_1.output)
  output_layer.forward(activation1.output)
  activation2.forward(output_layer.output)
  return activation2.output

In [33]:
def back_prop(fp):
  lr = torch.tensor(0.01)
  back1 = (fp[0][0]-y[0])*(1-fp[0][0])*fp[0][0]
  back2 = (fp[0][1]-y[1])*(1-fp[0][1])*fp[0][1]

  output_layer.weights[0][0] -= lr * back1*activation1.output[0][0]
  output_layer.weights[0][1] -= lr * back1*activation1.output[0][1]
  output_layer.weights[1][0] -= lr * back2*activation1.output[0][0]
  output_layer.weights[1][1] -= lr * back2*activation1.output[0][1]
  output_layer.weights[2][0] -= lr * back1*activation1.output[0][2]
  output_layer.weights[2][1] -= lr * back2*activation1.output[0][2]
  output_layer.weights[3][0] -= lr * back1*activation1.output[0][3]
  output_layer.weights[3][1] -= lr * back2*activation1.output[0][3]
  
  output_layer.biases[0][0] -= lr * back1
  output_layer.biases[0][1] -= lr * back2
  

  for i in range(hidden_layer_1.weights.shape[0]):
      for j in range(hidden_layer_1.weights.shape[1]):
        hidden_layer_1.weights[i][j] -= lr * (
            back1 * output_layer.weights[j][i] * X[i] +
            back2 * output_layer.weights[j][i] * X[i]
        ) * hidden_layer_1.output[0][j] * (1 - hidden_layer_1.output[0][j])
    # for j in range(hidden_layer.biases.shape[1]):
    #   hidden_layer.biases[0][j] -= lr * (
    #     back1 * output_layer.weights[j][0] +
    #     back2 * output_layer.weights[j][1]
    # ) * hidden_layer.output[0][j] * (1 - hidden_layer.output[0][j])

  hidden_layer_1.biases[0][0] -= lr * (back1 * output_layer.weights[0][0] + back2 * output_layer.weights[0][1] )  
  hidden_layer_1.biases[0][1] -= lr * (back1 * output_layer.weights[1][0] + back2 * output_layer.weights[1][1] ) 
  hidden_layer_1.biases[0][2] -= lr * (back1 * output_layer.weights[2][0] + back2 * output_layer.weights[2][1])
  hidden_layer_1.biases [0][3] -= lr * (back1 * output_layer.weights[3][0] + back2 * output_layer.weights[3, 1])
  

In [26]:
def error_calculation(y_true, y_pred):
  return torch.mean(0.5*(y_true - y_pred)**2)

In [27]:
loss = 0.0001

In [34]:
y_pred = forward_pass(X)
err = error_calculation(y, y_pred)
print("Initial loss:", err)
print("Initial prediction:",y_pred)

while err > loss:
  back_prop(y_pred)
  y_pred = forward_pass(X)
  err = error_calculation(y, y_pred)
print("Final loss:", err)
print("Final prediction:",y_pred)
print("Target value:",y)

Initial loss: tensor(0.2210)
Initial prediction: tensor([[0.0098, 0.0106]])
tensor([[0.0040, 0.0041],
        [0.0075, 0.0061],
        [0.0006, 0.0030],
        [0.0075, 0.0064]])
tensor([[0.0045, 0.0088, 0.0055, 0.0045],
        [0.0011, 0.0097, 0.0057, 0.0074]])
tensor([[0.5002, 0.5014, 0.5008, 0.5010]])
tensor([[0.0098, 0.0106]])
Final loss: tensor(9.9830e-05)
Final prediction: tensor([[0.0630, 0.9348]])
Target value: tensor([0.0500, 0.9500])
