In [1]:
# Import packages
import torch

In [2]:
# Define a Layer class that contains ReLU activation function

class Activation_ReLU:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

    # Apply activation functions
    self.output = torch.max(torch.tensor(0.0), self.output)
    return self.output


In [3]:
# Define a Layer class that contains Sigmoid activation function

class Activation_Sigmoid:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

    # Apply activation functions
    self.output = 1 / (1 + torch.exp(-self.output))

    return self.output



In [4]:
# Define a Layer class that contains Softmax activation function

class Activation_Softmax:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    multiplied_inputs = torch.matmul(inputs, self.weights) + self.biases

    # Apply activation functions
    exp_values = torch.exp(multiplied_inputs) - torch.max(inputs, axis=1,keepdims=True).values
    summed_input = exp_values.sum(dim=1, keepdim=True)
    probabilities = exp_values / summed_input
    self.output = probabilities

    return self.output


In [5]:
# Create a Neural Network that uses the ReLU activation function

class SimpleNeuralNetworkWithReLU:
    def __init__(self):
        # Define layers
        self.layer1_relu = Activation_ReLU(n_inputs=4, n_neurons=18)
        self.layer2_relu = Activation_ReLU(n_inputs=18, n_neurons=18)
        self.layer3_softmax = Activation_Softmax(n_inputs=18, n_neurons=3)  # Output layer with 3 neurons for classification

    def train(self, inputs):
        # Forward pass through each layer with manual activation functions
        out1 = self.layer1_relu.forward(inputs)
        out2 = self.layer2_relu.forward(out1)
        log_probabilities = self.layer3_softmax.forward(out2)  # Softmax for multiclass classification
        return log_probabilities

In [6]:
# Create a Neural Network that uses the Sigmoid activation function

class SimpleNeuralNetworkWithSigmoid:
    def __init__(self):
        # Define layers
        self.layer1 = Activation_Sigmoid(n_inputs=4, n_neurons=18)
        self.layer2 = Activation_Sigmoid(n_inputs=18, n_neurons=18)
        self.layer3 = Activation_Softmax(n_inputs=18, n_neurons=3)  # Output layer with 3 neurons for classification

    def train(self, inputs):
        # Forward pass through each layer with manual activation functions
        out1 = self.layer1.forward(inputs)
        out2 = self.layer2.forward(out1)
        log_probabilities = self.layer3.forward(out2)  # Softmax for multiclass classification
        return log_probabilities

### Testing the model that uses the ReLU activation function for the first two layer of the neural network.

In [21]:
model_relu = SimpleNeuralNetworkWithReLU()
input = torch.rand(2, 4)
print(input)
output = model_relu.train(input)
print(output)

tensor([[0.8317, 0.8812, 0.4141, 0.2984],
        [0.2336, 0.9730, 0.7667, 0.0312]])
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


In [23]:
model_sigmoid = SimpleNeuralNetworkWithSigmoid()
input2 = torch.rand(2, 4)
print(input2)
output2 = model_sigmoid.train(input2)
print(output2)

tensor([[0.1018, 0.4859, 0.2624, 0.8219],
        [0.3243, 0.4467, 0.0189, 0.2700]])
tensor([[0.3335, 0.3379, 0.3287],
        [0.3335, 0.3379, 0.3287]])


In [8]:
9

### Finding Cross Entropy Loss


In [19]:
def cross_entropy_loss(predictions, targets):
  size = predictions.shape[0]
  input_losses = -torch.log(predictions[range(size), targets])
  loss = torch.sum(input_losses) / size
  return loss

def accuracy(predictions, targets):
  pred_index = torch.argmax(predictions, axis=1)
  correct_predictions = torch.sum(pred_index == targets).item()
  accuracy = correct_predictions / len(targets)
  print(pred_index == correct_predictions)
  print("The number of correct predictions is: ", correct_predictions)
  return accuracy

In [10]:
input = torch.rand(5, 4)
targets = torch.tensor([1, 0, 2, 0, 1])

#### Test ReLU activation function

In [20]:
relu_predictions = model_relu.train(input)

loss = cross_entropy_loss(relu_predictions, targets)
print("The Cross Entropy Loss is: ", loss)

acc = accuracy(relu_predictions, targets)
print("the accuracy is: ", acc)



The Cross Entropy Loss is:  tensor(1.0986)
tensor([False, False, False, False, False])
The number of correct predictions is:  2
the accuracy is:  0.4


#### Test Sigmoid Activation Function

In [12]:
sigmoid_predictions = model_sigmoid.train(input)

loss = cross_entropy_loss(relu_predictions, targets)
print("The Cross Entropy Loss is: ", loss)

acc = accuracy(relu_predictions, targets)
print("the accuracy is: ", acc)


The Cross Entropy Loss is:  tensor(1.0986)
tensor([False, False, False, False, False])
The number of correct predictions is:  2
the accuracy is:  0.4


In [16]:
import torch.nn as nn

sigmoid_predictions = model_sigmoid.train(input)
# Use CrossEntropyLoss
criterion = nn.CrossEntropyLoss()
print(sigmoid_predictions)
# Calculate the loss
loss = criterion(sigmoid_predictions, targets)
loss


tensor([[0.3286, 0.3433, 0.3281],
        [0.3286, 0.3433, 0.3281],
        [0.3286, 0.3433, 0.3281],
        [0.3286, 0.3433, 0.3281],
        [0.3286, 0.3433, 0.3281]])


tensor(1.0976)