#### Name:  Yared Tsegaye Gizaw

#### ID:  UGR/8284/12

In [1]:
# Import packages
import torch

#### Activation Functions

In [2]:
def relu(inputs):
    return torch.maximum(torch.zeros_like(inputs), inputs)

def softmax(inputs):
    exp_values = torch.exp(inputs - torch.max(inputs, dim=1, keepdim=True).values)
    return exp_values / torch.sum(exp_values, dim=1, keepdim=True)

def sigmoid(inputs):
    return 1 / (1 + torch.exp(-inputs))
     

In [3]:
# Define a Layer class that contains ReLU activation function

class Activation_ReLU:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = torch.rand((n_inputs, n_neurons), requires_grad=True)
    self.biases = torch.zeros((1, n_neurons), requires_grad=True)

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

    # Apply activation functions
    self.output = relu(self.output)
#     print(self.output)
    return self.output


In [4]:
# Define a Layer class that contains Sigmoid activation function

class Activation_Sigmoid:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = torch.rand((n_inputs, n_neurons), requires_grad=True)
    self.biases = torch.zeros((1, n_neurons), requires_grad=True)

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

    # Apply activation functions
    self.output = sigmoid(self.output)
#     print(self.output)
    return self.output



In [5]:
# Define a Layer class that contains Softmax activation function

class Activation_Softmax:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = torch.rand((n_inputs, n_neurons), requires_grad=True)
    self.biases = torch.zeros((1, n_neurons), requires_grad=True)

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    weighted_sum = torch.matmul(inputs, self.weights) + self.biases

    # Apply activation functions
    self.output = softmax(weighted_sum)
#     print(self.output)
    return self.output


#### Neural Networks With Activation Functions

In [6]:
# Create a Neural Network that uses the ReLU activation function

class SimpleNeuralNetworkWithReLU:
    def __init__(self):
        # Define layers
        self.layer1 = Activation_ReLU(n_inputs=4, n_neurons=18)
        self.layer2 = Activation_ReLU(n_inputs=18, n_neurons=18)
        self.layer3 = Activation_Softmax(n_inputs=18, n_neurons=3)  # Output layer with 3 neurons for classification

    def train(self, inputs):
        # Forward pass through each layer with manual activation functions
        out1 = self.layer1.forward(inputs)
        out2 = self.layer2.forward(out1)
        log_probabilities = self.layer3.forward(out2)  # Softmax for multiclass classification
        return log_probabilities

In [7]:
# Create a Neural Network that uses the Sigmoid activation function

class SimpleNeuralNetworkWithSigmoid:
    def __init__(self):
        # Define layers
        self.layer1 = Activation_Sigmoid(n_inputs=4, n_neurons=18)
        self.layer2 = Activation_Sigmoid(n_inputs=18, n_neurons=18)
        self.layer3 = Activation_Softmax(n_inputs=18, n_neurons=3)  # Output layer with 3 neurons for classification

    def train(self, inputs):
        # Forward pass through each layer with manual activation functions
        out1 = self.layer1.forward(inputs)
        out2 = self.layer2.forward(out1)
        log_probabilities = self.layer3.forward(out2)  # Softmax for multiclass classification
        return log_probabilities

#### Cross Entropy Loss & Accuracy


In [8]:
def cross_entropy_loss(predictions, targets):
  size = predictions.shape[0]
  input_losses = -torch.log(predictions[range(size), targets])
  loss = torch.sum(input_losses) / size
  return loss

def accuracy(predictions, targets):
  pred_index = torch.argmax(predictions, axis=1)
  correct_predictions = torch.sum(pred_index == targets).item()
  accuracy_val = correct_predictions / len(targets)
  return accuracy_val, pred_index == targets

#### Compare ReLU and Sigmoid Outcomes

In [9]:
torch.manual_seed(20)
input = torch.rand(5, 4)
targets = torch.tensor([0, 1, 0, 2, 1])
input, targets

(tensor([[0.5615, 0.1774, 0.8147, 0.3295],
         [0.2319, 0.7832, 0.8544, 0.1012],
         [0.1877, 0.9310, 0.0899, 0.3156],
         [0.9423, 0.2536, 0.7388, 0.5404],
         [0.4356, 0.4430, 0.6257, 0.0379]]),
 tensor([0, 1, 0, 2, 1]))

#### Test ReLU activation function

In [12]:
def relu_test():
    model_relu = SimpleNeuralNetworkWithReLU()
    relu_predictions = model_relu.train(input)
    loss = cross_entropy_loss(relu_predictions, targets)
    accuracy_val, preds = accuracy(relu_predictions, targets)
    print("================ReLU Test===============")
    print("The Cross Entropy Loss is: ", loss.item())
    print("the accuracy is: ", accuracy_val)
    print(preds)

def sigmoid_test():
    model_sigmoid = SimpleNeuralNetworkWithSigmoid()
    sigmoid_predictions = model_sigmoid.train(input)
    loss = cross_entropy_loss(sigmoid_predictions, targets)
    accuracy_val, preds = accuracy(sigmoid_predictions, targets)
    
    print("\n\n================Sigmoid Test===============")
    print("The Cross Entropy Loss is: ", loss.item())
    print("the accuracy is: ", accuracy_val)
    print(preds)
    

#### Run Tests

In [13]:
relu_test()
sigmoid_test()

================ReLU Test===============
The Cross Entropy Loss is:  14.831993103027344
the accuracy is:  0.2
tensor([False, False, False,  True, False])


================Sigmoid Test===============
The Cross Entropy Loss is:  1.161668300628662
the accuracy is:  0.4
tensor([False,  True, False, False,  True])
